board/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('post.urls', namespace='post')),
    url(r'^accounts/',include('django.contrib.auth.urls')),
    url(r'^signup/$', views.signup, name='signup'),
]

post/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^post/(?P<id>\d+)/$', views.post_detail, name='post_detail'),
    url(r'^post/new/$', views.post_new, name='post_create'),
    url(r'^post/delete/$', views.post_delete, name='post_delete'),
    url(r'^post/update/(?P<id>\d+)/$', views.post_edit, name='post_update'),

    url(r'^comment/new/(?P<bidx>\d+)/$', views.comment_new, name='comment_create'),
    url(r'^comment/delete/$', views.comment_delete, name='comment_delete'),
]

post/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models



class BoardTbl(models.Model):
    idx = models.AutoField(primary_key=True)
    writer = models.IntegerField(blank=True, null=True)
    subject = models.CharField(max_length=255, blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'board_tbl'


class CommentTbl(models.Model):
    idx = models.AutoField(primary_key=True)
    bidx = models.IntegerField(blank=True, null=True)
    writer = models.IntegerField(blank=True, null=True)
    content = models.TextField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'comment_tbl'

board/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class SignupForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name',)

post/forms.py
from django import forms
from .models import BoardTbl, CommentTbl

class PostForm(forms.ModelForm):

    class Meta:
        model = BoardTbl
        fields = ('subject' , 'content')
        labels = {
            'subject' : '제목',
            'content' : '내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = CommentTbl
        fields = ('content',)
        labels = {
            'content' : '내용'
        }
        widgets = {
            'content' : forms.TextInput(),
        }

board/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib import messages
from .forms import SignupForm

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save();
            messages.success(request, '회원가입에 성공했습니다.')
            return redirect(settings.LOGIN_URL)
    else:
        form = SignupForm()
    return render(request, 'registration/signup_form.html', {'form':form})

post/views.py
from django.utils import timezone
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.http import JsonResponse
from .forms import PostForm, CommentForm
from .models import BoardTbl, CommentTbl

def index(request):
    posts = BoardTbl.objects.raw( # ORM 미사용
        'SELECT b.idx, u.last_name, u.first_name, b.subject, b.content, b.date '
        'FROM board_tbl b '
        'JOIN auth_user u '
        'ON b.writer = u.id'
    )
    count = len(list(posts));
    return render(request, 'post/index.html', {'posts':posts, 'count':count})


def post_detail(request,id):
    post = BoardTbl.objects.raw(
        'SELECT b.idx, u.last_name, u.first_name, b.subject, b.content, b.date '
        'FROM board_tbl b '
        'JOIN auth_user u '
        'ON b.writer = u.id '
        'WHERE idx = %s'
        ,[id])[0]

    comments = CommentTbl.objects.raw(
        'SELECT c.idx, u.last_name, u.first_name, c.content, c.date '
        'FROM comment_tbl c '
        'JOIN auth_user u '
        'ON c.writer = u.id '
        'WHERE bidx = %s'
        ,[id])

    form  = CommentForm()
    return render(request, 'post/detail.html', {'post':post, 'comments':comments, 'form':form})


@login_required
def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid(): # ORM 사용
            post = form.save(commit=False)
            post.writer = request.user.id
            post.date = timezone.localtime()
            post.save()
            messages.success(request, '게시글이 작성되었습니다.')
            return redirect('post:index')
    else:
        form = PostForm()
    return render(request, 'post/form.html', {'form':form})


@login_required
def post_edit(request, id):
    post = get_object_or_404(BoardTbl, idx=id)
    if post.writer != request.user.id:
        messages.error(request, '게시물 수정은 해당 작성자만 가능합니다.')
    else:
        if request.method == 'POST':
            form = PostForm(request.POST, instance=post)
            if form.is_valid():
                form.save() # 작성자와 게시글과 작성일은 그대로 나둠
                messages.success(request, '게시글이 수정되었습니다.')
        else:
            form = PostForm(instance=post)
            return render(request, 'post/form.html', {'form':form})
    return redirect('post:index')


@login_required
def post_delete(request):
    if request.method == 'POST':
        idx = request.POST['idx']
        post = get_object_or_404(BoardTbl, idx=idx)
        if post.writer != request.user.id:
            messages.error(request, '게시물 삭제은 해당 작성자만 가능합니다.')
        else:
            comments = CommentTbl.objects.filter(bidx=idx)
            post.delete()
            comments.delete() # CASCADE
            messages.success(request, '게시물이 삭제되었습니다.')
    return redirect('post:index')


@login_required
def comment_new(request, bidx):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.writer = request.user.id
            comment.date = timezone.localtime()
            comment.bidx = bidx
            comment.save()
            messages.success(request, '댓글이 작성되었습니다.')
        else:
            messages.error(request, '댓글 작성에 실패했습니다.')
    return redirect('post:post_detail',id=bidx)


@login_required
def comment_delete(request):
    if request.method == 'POST':
        idx = request.POST['idx']
        bidx = request.POST['bidx']
        comment = get_object_or_404(CommentTbl, idx=idx)
        if comment.writer != request.user.id:
            messages.error(request, '댓글 삭제은 해당 작성자만 가능합니다.')
        else:
            comment.delete()
            messages.success(request, '댓글이 삭제되었습니다.')
    return redirect('post:post_detail', id=bidx)

board/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>커뮤니티 사이트</title>
    <!-- 부트스트랩 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/gh/moonspam/NanumSquare@1.0/nanumsquare.css">
    {% load static %}
    <link rel="stylesheet" href="{% static 'common.css' %}">
    <link rel="stylesheet" href="{% block style %}{% endblock %}">
</head>
<body>
<div class="wrap">
    <header>
        <nav>
            <ul class="nav justify-content-end">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'login' %}">로그인</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">회원가입</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <span class="nav-link disabled">{{ user.last_name }}{{ user.first_name }}님</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'logout' %}?next={% url 'post:index' %}">로그아웃</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <h1 class="text-center">
            <a href="{% url 'post:index' %}">커뮤니티 사이트</a>
        </h1>
    </header>
    <section class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message.message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}

        {% endblock %}
    </section>
    <footer>
        <p class="text-center">
            Copyright &copy; 2018 정보처리산업기사 All Right Reserved
        </p>
    </footer>
</div>
</body>
</html>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script>
    {% block script %}
    {% endblock %}
</script>

post/templates/post/detail.html
{% extends 'layout.html' %}
{% load static %}
{% block style %}{% static 'css/detail.css' %}{% endblock %}
{% block content %}
    <article>
        <h2>게시물 조회</h2>
        <table>
            <tr>
                <td style="font-size:25px;">제목 : {{ post.subject }}</td>
            </tr>
            <tr>
                <td>작성자 :{{ post.last_name }}{{ post.first_name }}</td>
                <td>작성일 : {{ post.date|date:'Y-m-d H:i' }}</td>
            </tr>
        </table>
        <pre>{{ post.content }}</pre>
        <hr>

        <h4>댓글</h4>
        <ul class="comment">
            {% for comment in comments %}
                <li>
                    {{ comment.last_name }}{{ comment.first_name }} &nbsp;/
                    {{ comment.content }}&nbsp; /
                    {{ comment.date|date:'Y-m-d H:i' }} &nbsp;
                    {% if comment.writer == request.user.id %} /
                        <form action="{% url 'post:comment_delete' %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="idx" value="{{ comment.idx }}">
                            <input type="hidden" name="bidx" value="{{ post.idx }}">
                            <button type="submt" class="btn-small" >삭제</button>
                        </form>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>

        {% if user.is_authenticated %}
            <hr>
            <h4>댓글 작성</h4>
            <div>
                <form action="{% url 'post:comment_create' post.idx %}" method="POST" id="delete-form">
                    {% csrf_token %}
                    {% for field in form.visible_fields %}
                        {{ field }}
                    {% endfor %}
                    <button class="btn custom-btn">댓글 작성</button>
                </form>
            </div>
            <div class="btns">
                {% if request.user.id == post.writer %}
                    <a href="{% url 'post:index' %}">
                        <button class="btn">목록</button>
                    </a>
                    <form action="{% url 'post:post_delete' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="idx" value="{{ post.idx }}"></input>
                        <button class="btn">삭제</button>
                    </form>
                    <a href="{% url 'post:post_update' post.idx %}">
                        <button class="btn">수정</button>
                    </a>
                {% endif %}
            </div>
        {% endif %}
    </article>
{% endblock %}

post/templates/post/form.html
{% extends 'layout.html' %}
{% load static %}
{% block style %}{% static 'css/form.css' %}{% endblock %}
{% block content %}
    <article>
        <h2>게시물 작성</h2>
        <form action="" method="post">
        {% csrf_token %}
            <table>
                <tr>
                    <td>작성자: </td>
                    <td>{{ user.last_name }}{{ user.first_name }}</td>
                </tr>
                {% for field in form.visible_fields %}
                <tr>
                    <td>{{ field.label_tag }}</td>
                    <td>{{ field }}</td>
                </tr>
                {% endfor %}
                <tr>
                    <td colspan="2" style="text-align:right">
                        <a href="{% url 'post:index' %}">
                            <button type="button" class="btn">목록</button>
                        </a>
                        <button type="submit" class="btn">
                            완료
                        </button>
                        </td>
                </tr>
            </table>
        </form>
    </article>
{% endblock %}

post/templates/post/index.html
{% extends 'layout.html' %}
{% load staticfiles %}
{% block style %}{% static 'css/index.css' %}{% endblock %}
{% block content %}
    <article>
        <p>총 {{ count }}개의 게시물이 있습니다.</p>
        <table>
            <tr>
                <th>번호</th>
                <th>글쓴이</th>
                <th>제목</th>
                <th>날짜</th>
            </tr>
            {% for post in posts %}
                <tr>
                    <td>{{ post.idx }}</td>
                    <td>{{ post.last_name }}{{ post.first_name }}</td>
                    <td><a href="{% url 'post:post_detail' post.idx %}">{{ post.subject }}</a></td>
                    <td>{{ post.date|date:'Y-m-d H:i' }}</td>
                </tr>
            {% endfor %}
        </table>
         {% if user.is_authenticated %}
            <p class="post-create">
                <a href="{% url 'post:post_create' %}">
                    <button class="btn">글 작성</button>
                </a>
            </p>
        {% endif %}
    </article>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>커뮤니티 사이트</title>
    <!-- 부트스트랩 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<div class="wrap container-fluid">
    <header>
        <nav>
            <ul class="nav justify-content-end">
                {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'login' %}">로그인</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'signup' %}">회원가입</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <span class="nav-link disabled">{{ user.last_name }}{{ user.first_name }}님</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{% url 'logout' %}?next={% url 'post:index' %}">로그아웃</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post:post_create' %}">글 작성</a>
                    </li>
                {% endif %}
            </ul>
        </nav>
        <h1 class="text-center">
            <a href="{% url 'post:index' %}">커뮤니티 사이트</a>
        </h1>
    </header>
    <section class="container">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}" role="alert">
                    {{ message.message }}
                </div>
            {% endfor %}
        {% endif %}

        {% block content %}

        {% endblock %}
    </section>
    <footer>
        <p class="text-center">
            Copyright &copy; 2018 정보처리산업기사 All Right Reserved
        </p>
    </footer>
</div>
</body>
</html>
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script>
    {% block script %}
    {% endblock %}
</script>